apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-nemesys-certs-pvc
  namespace: nemesys
  labels:
    team: infra
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi